In [1]:
!python setup.py build_ext --inplace

running build_ext


できた関数をimportしてみる。

In [2]:
import from_ndarray

試しに、1次元のndarrayを作ってfrom_ndarray.func()で書き換えがうまくいくか確認する

In [3]:
import numpy as np
# 適当に0だけ入ったarrayをとる
temp = np.zeros(10)

In [4]:
temp

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
from_ndarray.func(temp)

In [6]:
temp

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

ちゃんと書き換わっていることが確認できる。

関数funcはdouble型のndarrayしか受け付けないようになっている。

以下のようにint型にしてみてfuncに入れるとエラーが出るはずである。

In [7]:
temp = np.zeros(5, dtype=np.int)

In [8]:
temp

array([0, 0, 0, 0, 0])

In [9]:
# from_ndarray.func(temp)